# Generated by Django 3.0.5 on 2021-03-28 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210328_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Разрешены символы алфавита, цифры и нижние подчеркивания.')]),
        ),
    ]
